[package]
name = "my_proc_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
<<<<<<< HEAD
ethers = "2.0.4"
reqwest = { version = "0.11.22", features = ["json"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["full"] }
my_proc_macro = { path = "/Users/NAOKI/Documents/udemy/rust_autogpt/playaround/my_proc_macro"}
ai_functions = "0.1.1"
=======
proc-macro2 = "1.0.56"
quote = "1.0.28"
syn = { version = "2.0.15", features = ["full"] }
>>>>>>> 29bf2ed52dbac44b7dd179e35d669c7bfc05f12f
